services:
    _defaults:
        public: false

    Versh23\ManticoreBundle\Command\PopulateCommand:
        arguments:
            - '@manticore.index_manager_registry'
            - '@doctrine'
        tags:
            - {name: 'console.command'}

    Versh23\ManticoreBundle\Command\IndexConfigCommand:
        arguments:
            - '@manticore.index_manager_registry'
        tags:
            - {name: 'console.command'}

    manticore.index_prototype:
        class: Versh23\ManticoreBundle\Index
        abstract: true
        arguments:
            -
            -
            -
            -
    manticore.index_manager_prototype:
        class: Versh23\ManticoreBundle\IndexManager
        abstract: true
        arguments:
            -
            -
            - '@doctrine'

    manticore.index_manager_registry:
        class: Versh23\ManticoreBundle\IndexManagerRegistry

    Versh23\ManticoreBundle\IndexManagerRegistry:
        alias: manticore.index_manager_registry

    manticore.listener_prototype:
        class: Versh23\ManticoreBundle\Listener
        abstract: true
        arguments:
            -